# 默认配置
server:
  port: 8080
#  servlet:
#    context-path: /



spring:
  datasource:
    name: test #数据库名
    url: jdbc:mysql://127.0.0.1:3306/test #url
    username: root  #用户名
    password:      #密码
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库链接驱动
#  profiles:
#    active: test

mybatis:
    mapper-locations: classpath:mapper/*.xml #配置映射文件
    type-aliases-package: com.example.test.bean #配置实体类


mybatis-puls:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath/*.xml #配置映射文件
  global-config:
    # 逻辑删除配置
     db-config:
       # 删除前
        logic-not-delete-value: 0
       # 删除后
        logic-delete-value: 1



